---
title: "numpy, pandas.DataFrame で多数決をとる"
date: 2024-05-12
categories: [ml]
---

多数決を取ったメモ。
今回は行ごとの最頻値を求める。

`scipy.stats.mode` を使うと楽。

[scipy.stats.mode — SciPy v1.13.0 Manual](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html#scipy.stats.mode)

In [1]:
import numpy as np
import scipy.stats as stats

In [2]:
a=np.array([[1,1,2],[3,4,5],[1,1,1]])
a

array([[1, 1, 2],
       [3, 4, 5],
       [1, 1, 1]])

In [3]:
b=np.array([[1,2,3],[3,4,1],[1,1,2]])
b

array([[1, 2, 3],
       [3, 4, 1],
       [1, 1, 2]])

In [4]:
c=np.hstack((a,b))
c

array([[1, 1, 2, 1, 2, 3],
       [3, 4, 5, 3, 4, 1],
       [1, 1, 1, 1, 1, 2]])

In [5]:
stats.mode(a,axis=1,keepdims=True)[0]

array([[1],
       [3],
       [1]])

In [6]:
stats.mode(b,axis=1,keepdims=True)[0]

array([[1],
       [1],
       [1]])

In [7]:
stats.mode(c,axis=1,keepdims=True)[0]

array([[1],
       [3],
       [1]])

## pandas.DataFrame

DataFrame にも `mode` 関数がある。

[pandas.DataFrame.mode — pandas 2.2.2 ドキュメント](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html)

In [8]:
import pandas as pd

In [9]:
df=pd.DataFrame(a)
df

0  1  2
0  1  1  2
1  3  4  5
2  1  1  1

In [10]:
df.mode(axis=1)

0    1    2
0  1.0  NaN  NaN
1  3.0  4.0  5.0
2  1.0  NaN  NaN

最頻値が複数あればその分の列が返るっぽい？ (ドキュメントに書いてなさそう)

In [11]:
df=pd.DataFrame(c)
df

0  1  2  3  4  5
0  1  1  2  1  2  3
1  3  4  5  3  4  1
2  1  1  1  1  1  2

In [12]:
df.mode(axis=1)

0    1
0  1.0  NaN
1  3.0  4.0
2  1.0  NaN